"""
Pydantic Schemas (Data Validation)

These classes validate data coming from the frontend.
They also define what data the API returns.

Key difference from models.py:
- models.py: Database structure
- schemas.py: API request/response structure
"""

from pydantic import BaseModel
from datetime import datetime
from typing import List, Optional


class InvoiceItemBase(BaseModel):
    """
    Base schema for Invoice Items (shared between Create and Read)

    This is the minimum required data for an item.
    Used as parent class for more specific schemas.
    """

    description: str  # Required text field
    hsn: str  # HSN/SAC code
    qty: float  # Quantity (can be decimal)
    rate: float  # Price per unit


class InvoiceItemCreate(InvoiceItemBase):
    """
    Schema for creating a new invoice item

    Used when frontend sends item data in create invoice request.
    No 'id' field because it's auto-generated by database.
    """
    pass  # Inherits all fields from InvoiceItemBase


class InvoiceItem(InvoiceItemBase):
    """
    Schema for reading invoice item data

    Includes fields returned from API.
    Pydantic automatically converts database model to this schema.
    """

    id: int  # Now we include the ID (generated by database)
    invoice_id: int

    class Config:
        # from_attributes=True: Convert SQLAlchemy model to Pydantic model
        # Allows doing: InvoiceItem.from_orm(database_item)
        from_attributes = True


class InvoiceBase(BaseModel):
    """
    Base schema for Invoices (shared fields)

    Common fields needed for both create and read operations.
    """

    invoice_no: str
    date: str  # Format: YYYY-MM-DD
    company_name: str
    company_address: str
    company_gstin: str
    client_name: str
    client_address: str
    client_gstin: str
    client_work_order: str
    bank_details: str
    bank_account: str
    bank_ifsc: str


class InvoiceCreate(InvoiceBase):
    """
    Schema for creating a new invoice

    Used when frontend sends data to create an invoice.
    Includes the items list.
    """

    items: List[InvoiceItemCreate]  # List of items in this invoice


class InvoiceUpdate(BaseModel):
    """
    Schema for updating an invoice

    Optional fields (Optional[type]) means they can be None.
    Frontend can update just one field without sending all fields.
    """

    invoice_no: Optional[str] = None
    date: Optional[str] = None
    client_name: Optional[str] = None
    client_address: Optional[str] = None
    client_gstin: Optional[str] = None
    client_work_order: Optional[str] = None
    items: Optional[List[InvoiceItemCreate]] = None


class Invoice(InvoiceBase):
    """
    Schema for reading invoice data from API

    This is what the API returns when you request an invoice.
    Includes all fields plus calculated amounts and items.
    """

    id: int  # ID field (comes from database)
    subtotal: float
    sgst: float
    cgst: float
    grand_total: float
    items: List[InvoiceItem]  # All items for this invoice
    created_at: datetime  # When created
    updated_at: datetime  # When last updated

    class Config:
        from_attributes = True  # Convert SQLAlchemy model to Pydantic


class InvoiceList(BaseModel):
    """
    Schema for listing all invoices (simplified)

    When returning list of invoices, don't need full details for each.
    Frontend can click on one to get full details.
    """

    id: int
    invoice_no: str
    date: str
    client_name: str
    grand_total: float
    created_at: datetime

    class Config:
        from_attributes = True
